# Generated by Django 5.1 on 2024-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriere', models.CharField(max_length=200)),
            ],
        ),
    ]
