# Generated by Django 5.1 on 2024-08-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='produs',
            name='pret',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='produs',
            name='categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.categorie'),
            preserve_default=False,
        ),
    ]
