# Generated by Django 5.1 on 2024-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorie_alter_produs_pret_produs_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livrare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=200)),
                ('numar_telefon', models.IntegerField(max_length=10)),
                ('metoda_plata', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('produse', models.ManyToManyField(to='shop.produs')),
            ],
        ),
    ]
