# Generated by Django 5.1 on 2024-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_livrare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrare',
            name='status',
        ),
        migrations.AlterField(
            model_name='livrare',
            name='numar_telefon',
            field=models.IntegerField(),
        ),
    ]
